name: Test

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    # This job runs on PR creation and updates
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Test with Maven
        run: mvn test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          docker build -t deepthought42/visual-design-audit:${{ env.BRANCH_NAME }} .
          docker tag deepthought42/visual-design-audit:${{ env.BRANCH_NAME }} deepthought42/visual-design-audit:latest
