name: Build, Push, Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Test with Maven
        run: mvn test

  bump-version:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node Modules
        run: npm install
        
      - name: Install dependencies
        run: npm ci

      - name: Determine and bump version with Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Extract new version from pom.xml
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
          
  build-and-release:
    needs: bump-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.bump-version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          docker build -t deepthought42/visual-design-audit:${{ env.VERSION }} .
          docker tag deepthought42/visual-design-audit:${{ env.VERSION }} deepthought42/visual-design-audit:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push deepthought42/visual-design-audit:${{ env.VERSION }}
          docker push deepthought42/visual-design-audit:latest
      
  github-release:
    needs: bump-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.bump-version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Test with Maven
        run: mvn install -DskipTests

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: CHANGELOG.md
          files: PageBuilder-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
